### ISSUE TITLE
InflateException:

### ISSUE THREAD

**Issue by tntkhang** [lopspower/RateBottomSheet#9]
I can't use the library due to this exception:

> :layout/rate_bottom_sheet_layout: Error inflating class com.google.android.material.button.MaterialButton

How can i fix it, I add the RateBottomSheet init in the MainActivity

**Comment by lopspower** [comment]
This library depends on MaterialDesign to be able to design the buttons with the color of the theme that is currently used.

This dependency is automatically integrated into the library. It is defined in `.pom`

```xml
<project ...>
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.mikhaellopez</groupId>
  <artifactId>ratebottomsheet</artifactId>
  <version>1.1.0</version>
  <packaging>aar</packaging>
  <dependencies>
    <dependency>
      <groupId>com.google.android.material</groupId>
      <artifactId>material</artifactId>
      <version>1.1.0</version>
    </dependency>
  </dependencies>
</project>
```

Since the last version of **Material Design 1.1.0** you absolutely must use a Material Design theme in this way:

```xml
<style name="Base.V1.Theme" parent="Theme.MaterialComponents.Light.DarkActionBar">
    <item name="colorPrimary">@color/primary</item>
    <item name="colorPrimaryDark">@color/primary_dark</item>
    <item name="colorAccent">@color/accent</item>
</style>
```
